name: call e2e

env:
  CLUSTER_NAME: spider
  E2E_TIME_OUT: 60m
  PERFORMANCESCRIPT: "./tools/scripts/e2eperformance.sh"
  ONLINE_REGISTER: ghcr.io
  BUILD_PLATFORM: linux/amd64,linux/arm64
  ONLINE_REGISTER_USER: ${{ github.actor }}
  ONLINE_REGISTER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_call:
    inputs:
      ip_family:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      ref:
        required: false
        type: string
      push:
        required: false
        type: boolean
      charts:
        required: false
        type: string

jobs:
  call_e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prepare
        run: |
          echo "===== image "
          echo "ci image tag: ghcr.io/${{ github.repository }}/controller-ci:${{ inputs.image_tag }}"
          echo "ci race image tag: ghcr.io/${{ github.repository }}/controller-ci:${{ inputs.image_tag }}-race"
          echo "ci image tag: ghcr.io/${{ github.repository }}/agent-ci:${{ inputs.image_tag }}"
          echo "ci race image tag: ghcr.io/${{ github.repository }}/agent-ci:${{ inputs.image_tag }}-race"
          echo "===== chart "
          echo "chart package artifact: ${{ inputs.charts }}"
          TMP=` date +%m%d%H%M%S `
          E2E_CLUSTER_NAME="spiderpool${TMP}"
          echo ::set-output name=clusterName::${E2E_CLUSTER_NAME}

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.0
          id: go

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.1

      # commit sha is used for image tag
      - name: Getting image tag
        id: tag
        run: |
          echo ${{ github.event_name }}
          if ${{ inputs.ref != '' }}; then
              echo "trigger by workflow_call"
              echo ::set-output name=tag::${{ inputs.ref }}
              echo ::set-output name=push::${{ inputs.push }}
          elif ${{ github.event_name == 'push' }} ; then
              echo "trigger by push"
              echo ::set-output name=tag::${{ github.sha }}
              echo ::set-output name=push::false
          elif ${{ github.event_name == 'pull_request_target' }} ; then
              echo "trigger by pull_request_target"
              echo ::set-output name=tag::${{ github.event.pull_request.head.sha }}
              echo ::set-output name=push::false
          elif ${{ github.event_name == 'workflow_run' }} ; then
              echo "trigger by workflow_run"
              echo ::set-output name=tag::main
              echo ::set-output name=push::false
          else
              echo "trigger by ${{ github.event_name }}"
              echo ::set-output name=tag::${{ github.sha }}
              echo ::set-output name=push::false
          fi

      - name: Login to online register
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ env.ONLINE_REGISTER_USER }}
          password: ${{ env.ONLINE_REGISTER_PASSWORD }}
          registry: ${{ env.ONLINE_REGISTER }}

      # checkout the changed code
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ steps.tag.outputs.tag }}

      - name: Getting Build Arg
        id: arg
        continue-on-error: false
        run: |
          GIT_COMMIT_VERSION=$( git show -s --format='format:%H')
          GIT_COMMIT_TIME=$( git show -s --format='format:%aI')
          echo ::set-output name=commitver::${GIT_COMMIT_VERSION}
          echo ::set-output name=committime::${GIT_COMMIT_TIME}

      # Import GitHub's cache build to docker cache
      # - name: Docker build agent
      #   uses: docker/build-push-action@v4.0.0
      #   with:
      #     context: .
      #     file: ./images/spiderpool-agent/Dockerfile
      #     push: true
      #     tags: ghcr.io/cyclinder/test1/agent:dev-race

      # # Import GitHub's cache build to docker cache
      # - name: Docker build controller
      #   uses: docker/build-push-action@v4.0.0
      #   with:
      #     context: .
      #     file: ./images/spiderpool-controller/Dockerfile
      #     push: true
      #     tags: ghcr.io/cyclinder/test1/controller:dev-race

      # https://github.com/helm/kind-action
      - name: Install Kind Bin
        uses: helm/kind-action@v1.7.0
        with:
          install_only: true

      - name: Install Tools
        run: |
          # install kind/p2ctl/helm/ginkgo
          bash ./test/scripts/install-tools.sh

      - name: Login to online register
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ env.ONLINE_REGISTER_USER }}
          password: ${{ env.ONLINE_REGISTER_PASSWORD }}
          registry: ${{ env.ONLINE_REGISTER }}

      - name: List docker Images
        run: |
          docker pull ghcr.io/cyclinder/test1/controller:dev-race
          docker pull ghcr.io/cyclinder/test1/agent:dev-race
          docker pull ghcr.io/cyclinder/test2/agent:dev
          docker pull ghcr.io/cyclinder/test2/controller:dev

      # test against commit version
      - name: Setup Kind Cluster
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 20
          max_attempts: 3
          shell: bash
          command: |
            make e2e_init -e E2E_CLUSTER_NAME=${{ steps.prepare.outputs.clusterName }} \
                -e TEST_IMAGE_TAG=dev-race \
                -e SPIDERPOOL_AGENT_IMAGE_NAME=agent  \
                -e SPIDERPOOL_CONTROLLER_IMAGE_NAME=controller \
                -e E2E_IP_FAMILY=${{ inputs.ip_family }} -e PYROSCOPE_LOCAL_PORT=""

      - name: Run e2e Test
        id: run_e2e
        continue-on-error: true
        run: |
          echo ${{ github.event.inputs.labels }}
          RESULT=0
          make e2e_test -e E2E_CLUSTER_NAME=${{ steps.prepare.outputs.clusterName }}  \
              -e E2E_GINKGO_LABELS=${{ inputs.ref.e2e_labels }} \
              -e E2E_TIMEOUT=${{ env.E2E_TIME_OUT }} \
              -e E2E_IP_FAMILY=${{ inputs.ip_family }} || RESULT=1
          if ((RESULT==0)) ; then
              echo ::set-output name=pass::true
          else
              echo ::set-output name=pass::false
          fi
          if [ -f "test/e2edebugLog" ] ; then
              echo ::set-output name=updaloadlog::true
          else
              echo ::set-output name=updaloadlog::false
          fi
          if [ -f "./e2ereport.json" ] ; then
              echo "error, did not find e2e report"
              echo ::set-output name=upload::true
          else
              echo ::set-output name=upload::false
          fi

      - name: Upload e2e log
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ inputs.ip_family }}-debuglog.txt
          path: test/e2edebugLog.txt
          retention-days: 7

      - name: Upload e2e report
        if: ${{ steps.run_e2e.outputs.upload == 'true' }}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ inputs.ip_family }}-e2ereport.json
          path: e2ereport.json
          retention-days: 1

      - name: Show e2e Result
        run: |
          if ${{ steps.run_e2e.outputs.pass == 'true' }} ;then
              exit 0
          else
              exit 1
          fi

      - name: Get the E2E Performance Result For Dual-stack
        id: get_performance
        if: ${{ inputs.ip_family == 'dual' }}
        shell: bash
        run: |
          # sudo apt-get install -y jq
          TOOL_PATH=${{ env.PERFORMANCESCRIPT }}
          TODO_STATUS=$( ${TOOL_PATH}  "e2ereport.json"  )
          # echo "PERFORMANCE=${TODO_STATUS}" >> $GITHUB_ENV
          echo ::set-output name=result::${TODO_STATUS}

      - name: Update Badge For Dual-stack
        if: ${{ steps.get_performance.outputs.result != '' && inputs.ip_family == 'dual' }}
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.WELAN_PAT }}
          gistID: 38d00a872e830eedb46870c886549561
          filename: spiderpoolperformance.json
          label: performance
          message: ${{ steps.get_performance.outputs.result }}
          color: lightgrey
